version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - pg
      - pgadmin

  pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=mail@domain.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - 9000:80
    depends_on:
      - pg
